services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_USER=${USERNAME_DB}
    ports:
      - "5432"
    restart: always
